# Generated by Django 2.1 on 2018-10-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(max_length=200)),
                ('placement', models.IntegerField()),
                ('exposure', models.FloatField()),
                ('mu', models.FloatField()),
                ('sigma', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=200)),
                ('ruleset', models.CharField(max_length=200)),
                ('video', models.URLField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unseeded_tournaments_played', models.IntegerField()),
                ('unseeded_matches_played', models.IntegerField()),
                ('seeded_tournaments_played', models.IntegerField()),
                ('seeded_matches_played', models.IntegerField()),
                ('other_tournaments_played', models.IntegerField()),
                ('other_matches_played', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Player')),
            ],
        ),
        migrations.CreateModel(
            name='RemovedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('challonge_id', models.CharField(max_length=200)),
                ('challonge_url', models.URLField()),
                ('date', models.DateField()),
                ('notability', models.CharField(max_length=200)),
                ('ruleset', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tournaments_organized', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentVod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizers',
            field=models.ManyToManyField(to='leaderboards.TournamentOrganizer'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Player'),
        ),
        migrations.AddField(
            model_name='removeditem',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loses', to='leaderboards.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='leaderboards.Player'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Player'),
        ),
    ]
