# Generated by Django 2.1 on 2018-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_auto_20181002_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerAliases',
            new_name='PlayerAlias',
        ),
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ruleset',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
