# Generated by Django 2.1 on 2018-10-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0005_auto_20181003_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesetPerRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('ruleset', models.CharField(max_length=200, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='tournaments_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='other_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='other_tournaments_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='seeded_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='seeded_tournaments_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='unseeded_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='unseeded_tournaments_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='leaderboards.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Tournament'),
        ),
        migrations.AddField(
            model_name='rulesetperround',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins_round', to='leaderboards.Player'),
        ),
    ]
