# Generated by Django 2.1 on 2018-10-09 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboards', '0007_teammatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=200)),
                ('stat_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleset', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='other_matches_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='other_tournaments_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='seeded_matches_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='seeded_tournaments_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='unseeded_matches_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='unseeded_tournaments_played',
        ),
        migrations.AlterField(
            model_name='match',
            name='ruleset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Ruleset'),
        ),
        migrations.AlterField(
            model_name='rulesetperround',
            name='ruleset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Ruleset'),
        ),
        migrations.AlterField(
            model_name='teammatch',
            name='ruleset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Ruleset'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='challonge_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='challonge_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='organizers',
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ruleset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Ruleset'),
        ),
        migrations.DeleteModel(
            name='TournamentOrganizer',
        ),
        migrations.AddField(
            model_name='playerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Player'),
        ),
    ]
