# Generated by Django 2.1 on 2018-10-09 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboards', '0008_auto_20181009_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='organizers',
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
