# Generated by Django 2.1 on 2018-10-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0009_auto_20181009_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='exposure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='mu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='placement',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='sigma',
            field=models.FloatField(null=True),
        ),
    ]
