# Generated by Django 2.1 on 2018-10-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0011_auto_20181012_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Ruleset'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='rulesetperround',
            name='ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Ruleset'),
        ),
        migrations.AlterField(
            model_name='teammatch',
            name='ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Ruleset'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Player'),
        ),
    ]
