# Generated by Django 2.1 on 2018-11-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0013_auto_20181012_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='ruleset',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='tournamentvod',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='video',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='stat_name',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='stat_number',
        ),
        migrations.AddField(
            model_name='match',
            name='loser_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_loses', to='leaderboards.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='leaderboards.Team'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rulesetperround',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_wins', to='leaderboards.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_wins', to='leaderboards.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_loses', to='leaderboards.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.AllowedScore'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='leaderboards.Player'),
        ),
        migrations.AlterField(
            model_name='rulesetperround',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_wins', to='leaderboards.Player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_wins', to='leaderboards.Player'),
        ),
        migrations.DeleteModel(
            name='TeamMatch',
        ),
        migrations.DeleteModel(
            name='TournamentVod',
        ),
        migrations.AddField(
            model_name='vod',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Match'),
        ),
        migrations.AddField(
            model_name='vod',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Tournament'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Stat'),
        ),
    ]
