# Generated by Django 2.1 on 2018-11-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0014_auto_20181103_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['placement']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ruleset',
            options={'ordering': ['ruleset']},
        ),
    ]
