# Generated by Django 2.1 on 2018-11-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0015_auto_20181103_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedscore',
            options={'ordering': ['score']},
        ),
    ]
