# Generated by Django 2.2.6 on 2019-10-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0017_auto_20181108_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['exposure']},
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='placement',
        ),
    ]
