# Generated by Django 2.2.6 on 2019-10-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0018_auto_20191010_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-exposure']},
        ),
    ]
