# Generated by Django 2.2.6 on 2019-10-10 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0019_auto_20191010_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_played',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
