# Generated by Django 2.2.6 on 2019-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0020_player_last_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_played',
            field=models.DateField(null=True),
        ),
    ]
