# Generated by Django 2.1 on 2020-03-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0021_auto_20191010_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
